num1 = int(input("Enter your first number: "))
num2 = int(input("Enter your secind number: "))
print("Addition: ",num1+num2)
print("Subtraction: ",num1-num2)
print("Multiplication: ",num1*num2)
print("Division: ",num1/num2)
print("Modulus: ",num1%num2)
name = input("Enter your name: ")
age = input("Enter your age: ")
print("Hello",name)
print("You are",age,"years old")
length = int(input("Enter length: "))
width = int(input("Enter width: "))
print("Area = ",length*width)